### ISSUE TITLE
Some songs doesn't show the runtime

### ISSUE THREAD

**Issue by Spaceshiprace** [Malopieds/InnerTune#67]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

search for any album and you will notice that some songs has no runtime shown 

### Expected behavior

show the runtime for the song

### Actual behavior

it doesn't show

### Logs

non

### InnerTune version

0.5.7

### Android version

Android 12

### Additional information

appreciate all the work u put in the app to make it better ❤️

**Comment by EisregenHaha** [comment]
peak album

**Comment by Spaceshiprace** [comment]
> peak album

It got some bangers

**Comment by EisregenHaha** [comment]
> > peak album
> 
> It got some bangers

it got only bangers u mean

**Comment by Spaceshiprace** [comment]
Mmm.. I mean there's alot of holes in it ngl

**Comment by EisregenHaha** [comment]
> Mmm.. I mean there's alot of holes in it ngl

no.

**Comment by Spaceshiprace** [comment]
> no.

okay 🤷

**Comment by Spaceshiprace** [comment]
@Malopieds just to clarify this issue is still not fixed, even if you closed it as completed but I'm still seeing songs without their runtimes shown and you can check that too.

**Comment by EisregenHaha** [comment]
> @Malopieds just to clarify this issue is still not fixed, even if you closed it as completed but I'm still seeing songs without their runtimes shown and you can check that too.

it actually was fixed im pretty sure but its broken again lmfao. i personally checked after it was marked solved since i was interested in the issue too

**Comment by Spaceshiprace** [comment]
> > @Malopieds just to clarify this issue is still not fixed, even if you closed it as completed but I'm still seeing songs without their runtimes shown and you can check that too.
> 
> it actually was fixed im pretty sure but its broken again lmfao. i personally checked after it was marked solved since i was interested in the issue too

did you have any idea why its been broken since it was fixed ?

**Comment by Spaceshiprace** [comment]
@Malopieds i have to tell you that this issue still occurs in the latest version, i hope you can fix it

**Comment by EisregenHaha** [comment]
> @Malopieds i have to tell you that this issue still occurs in the latest version, i hope you can fix it

u sure? can you name an album name cuz melodic blue which previously had the bug now works

**Comment by Spaceshiprace** [comment]
@EisregenHaha 
its random i can't name a specific album where the issue occurs, you can find it anywhere just randomly or at least that what's happening with me every time

**Comment by Spaceshiprace** [comment]
I've been waiting for a fix for this issue for a long time but it's still there
